### ISSUE TITLE
Network Fails with panic: interface conversion: interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by jasonmcintosh** [sky-uk/terraform-provider-infoblox#77]
Thought I'd share...debugging now (not the v.0.2.1 is a mistype on my part when building).

panic: interface conversion: interface {} is nil, not []interface {}
2018-02-28T13:38:41.361-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1:
2018-02-28T13:38:41.361-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: goroutine 48 [running]:
2018-02-28T13:38:41.361-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: github.com/sky-uk/terraform-provider-infoblox/vendor/github.com/sky-uk/skyinfoblox.Client.FilterProfileAttrs(0xc42016fb90, 0x5, 0xc4201ab740, 0x14, 0xc42016fba0, 0x5, 0xc42016fb60, 0xb, 0x1, 0xc42038ce10, ...)
2018-02-28T13:38:41.361-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: 	/Users/jasonmcintosh/development/go/src/github.com/sky-uk/terraform-provider-infoblox/vendor/github.com/sky-uk/skyinfoblox/api.go:344 +0xb68
2018-02-28T13:38:41.361-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: github.com/sky-uk/terraform-provider-infoblox/vendor/github.com/sky-uk/skyinfoblox.Client.Create(0xc42016fb90, 0x5, 0xc4201ab740, 0x14, 0xc42016fba0, 0x5, 0xc42016fb60, 0xb, 0x1, 0xc42038ce10, ...)
2018-02-28T13:38:41.362-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: 	/Users/jasonmcintosh/development/go/src/github.com/sky-uk/terraform-provider-infoblox/vendor/github.com/sky-uk/skyinfoblox/api.go:79 +0x576
2018-02-28T13:38:41.362-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: github.com/sky-uk/terraform-provider-infoblox/infoblox.CreateResource(0x16f8715, 0x7, 0xc420448000, 0xc420335880, 0x16327c0, 0xc42038ce40, 0x1725501, 0xc420335880)
2018-02-28T13:38:41.362-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: 	/Users/jasonmcintosh/development/go/src/github.com/sky-uk/terraform-provider-infoblox/infoblox/resource.go:28 +0x454
2018-02-28T13:38:41.362-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: github.com/sky-uk/terraform-provider-infoblox/infoblox.resourceNetworkCreate(0xc420335880, 0x16327c0, 0xc42038ce40, 0x0, 0x0)
2018-02-28T13:38:41.362-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: 	/Users/jasonmcintosh/development/go/src/github.com/sky-uk/terraform-provider-infoblox/infoblox/resource_network.go:229 +0x62
2018-02-28T13:38:41.362-0600 [DEBUG] plugin.terraform-provider-infoblox_v0.2.1: github.com/sky-uk/terraform-provider-infoblox/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420374a20, 0xc420160960, 0xc4203b93a0, 0x16327c0, 0xc42038ce40, 0xc4203

**Comment by jasonmcintosh** [comment]
BLEH - tied to the wapi version.  Will do a docs update and pull request.
